export const primaryColor = '#45BF55'
export const borderColor = '#e7e7e7'
export const white = '#ffffff'
export const black = '#000000'
export const offWhite = '#FFFAFA'
export const primaryFontColor = '#707070'
